linters-settings:
    dupl:
        threshold: 100
    errorlint:
        errorf: true
    errcheck:
        check-type-assertions: true
        check-blank: true
    exhaustive:
        check-generated: false
        default-signifies-exhaustive: false
    funlen:
        lines: 65
        statements: 40
    gocognit:
        min-complexity: 15
    gocyclo:
        min-complexity: 10
    goconst:
        min-len: 2
        min-occurrences: 2
    gocritic:
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - dupImport
            - unnecessaryBlock
    gofumpt:
        extra-rules: true
    gomnd:
        settings:
            mnd:
                checks:
                    - argument
                    - case
                    - condition
                    - operation
                    - return
    govet:
        check-shadowing: true
    misspell:
        locale: US
    nestif:
        min-complexity: 4
    nolintlint:
        require-explanation: true
        require-specific: true
    depguard:
      rules:
        main:
          allow:
            - golang.org/x/text/cases
            - golang.org/x/text/language
            - gorm.io/gorm
            - gorm.io/gorm/logger
            - github.com/spf13/viper
            - github.com/gin-gonic/gin
            - gorm.io/driver/postgres
            - github.com/rs/zerolog
            - github.com/slack-go/slack
            - github.com/swaggo/gin-swagger
            - github.com/stretchr/testify/mock
            - github.com/stretchr/testify/suite
            - github.com/go-playground/validator/v10
            - github.com/javiertelioz/clean-architecture-go/pkg/
            - github.com/javiertelioz/clean-architecture-go/config
            - github.com/javiertelioz/clean-architecture-go/test/application/user_cases/user/mocks

linters:
    disable-all: true
    enable:
        - asciicheck
        - bodyclose
        - cyclop
        - deadcode
        - depguard
        - dogsled
        - dupl
        - durationcheck
        - errcheck
        - errorlint
        - exhaustive
        - exportloopref
        - forbidigo
        - funlen
        - gci
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - godox
        - goerr113
        - gofmt
        - gofumpt
        - goimports
        - gomnd
        - gomodguard
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - makezero
        - misspell
        - nakedret
        - nestif
        - nlreturn
        - noctx
        - nolintlint
        - paralleltest
        - predeclared
        - revive
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        - structcheck
        - stylecheck
        - tparallel
        - thelper
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - wsl
        - whitespace

# disable:
#    - exhaustivestruct
#    - ifshort
#    - goheader
#    - prealloc
#    - testpackage
#    - wrapcheck

issues:
    exclude-rules:
        - path: integration-test
          linters:
              - paralleltest
              - godot
        - path: internal/controller/http
          linters:
              - godot

run:
    skip-dirs:
        - docs
