gin_mode: debug
app_env: local
app_name: Example Clean Architecture

server:
    port: 8080
    host: localhost

database:
    host: localhost
    user: postgres
    password: password
    name: postgres
    port: 5432
    driver: postgres
    schema: clean-arquitecture-go
    sslmode:
    timezone:

jwt:
    secret: secret
    expiration: 1d

crypto:
    salt: 10

cors:
    allow_credentials: true
    max_age: 12
    allowed_origins:
        - '*'
    allow_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "PATCH"
        - "DELETE"
        - "HEAD"
        - "OPTIONS"
    allow_headers:
        - "Origin"
        - "Content-Length"
        - "Content-Type"
    expose_headers:
        - '*'
