name: Go Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Upload Coverage to Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Run tests and get coverage
        run: |
          mkdir -p coverage
          go test ./test/... -coverpkg=./pkg/... -coverprofile=coverage.out
          go test -v -race -cover -covermode=atomic ./test/... -coverpkg=./pkg/... -coverprofile=coverage/coverage.out -shuffle=on
          go tool cover -func=coverage/coverage.out
          go tool cover -html=coverage/coverage.out -o coverage/coverage.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage.out
